644 7e5 create workspace service
cezarmocanu/semicolon-task-manager-skillbrains pull request #13
Opened 2023-05-02 14:27 UTC by AdrianaGroza

2023-05-02 16:27 UTC, cezarmocanu requested changes

2023-05-02 16:27 UTC, cezarmocanu commented on src/services/workspace-service.js
> +        dispatch(setWorkspace(data));
```js
return data; 
```

2023-05-02 16:27 UTC, cezarmocanu commented on src/services/workspace-service.js
> +        dispatch(setWorkspace(data));
dispatch is undefined

2023-05-02 16:27 UTC, cezarmocanu commented on src/services/workspace-service.js
> +        dispatch(setWorkspace([]));
dispatch is undefined
setWorkspace can only be used inside a react component

2023-05-02 16:27 UTC, cezarmocanu commented on src/services/workspace-service.js
> +const getWorkspace = async () => {
rename into getWorkspaces because it is a list

2023-05-02 16:27 UTC, cezarmocanu commented on src/store/slices/workspace-slice.js
> +        return action.payload;
state = action.payload;
return state;

2023-05-02 16:27 UTC, cezarmocanu commented on src/constants/api.js
>  	AUTH: {
You can add the code below insede the test component to check if your service works properly
```js
useEffect(() => {
		workspaceService.getWorkspace();
	}, []);
```

2023-05-02 16:27 UTC, cezarmocanu commented on src/services/workspace-service.js
> +	const response = await fetch(ENDPOINTS.AUTH.WORKSPACE.USER_WORKSPACE, {
remove ```AUTH``` form object

2023-05-02 16:27 UTC, cezarmocanu commented on src/services/workspace-service.js
> +        dispatch(setWorkspace([]));
return [] in case of error or other status

2023-05-02 16:27 UTC, cezarmocanu commented on src/constants/api.js
>  	AUTH: {
Also modiffy this useEffect hook to dispaly the data received from the service function

2023-05-02 16:32 UTC, AleBarboni commented on src/store/slices/workspace-slice.js
> +
remove white space

2023-05-08 16:58 UTC, cezarmocanu approved these changes

2023-05-08 16:58 UTC, HalaszPaul approved these changes

2023-05-08 16:59 UTC, AleBarboni approved these changes

2023-05-08 16:59 UTC, ramona5lodea approved these changes

2023-05-08 16:59 UTC, merged