Create-Task-Extract-Data
cezarmocanu/semicolon-task-manager-skillbrains pull request #35
Opened 2023-05-14 08:10 UTC by AleBarboni

2023-05-14 10:31 UTC, cezarmocanu requested changes

2023-05-14 10:31 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
> +	}
This function is not needed as we can transform the selected date to js date using `date.toDate()`

2023-05-14 10:31 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
> +	const [description, setDescription] = useState("");
Having multiple fields with separate states is very work intensive and leads to multiple event handlers. It is enough to have a single formState object such as
```js
{
  taskName: string,
  priority: string,
  dueDate: Date,
  description: string,
}

```

2023-05-14 10:31 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
>  	const dispatch = useDispatch();
Dispatch is not needed as it does not call any redux actions

2023-05-14 10:31 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
> +	const tomorrow = dayjs().add(1, "day");
add useMemo as they should not be recomputed every render

2023-05-14 10:31 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
> +	const handleChangeDueDate = (selectDate) => {
for the handleChangeDueDate is is enough to use 
`setDueDate(selectedDate.toDate())`

Docs
https://day.js.org/docs/en/display/as-javascript-date

2023-05-14 10:31 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
> +	};
You can only have two handlers, one for the handleChangeDueDate and one for handleFieldChange as such

```js
const handleFieldChange = (event) => {
      setFormState({...formState, [event.target.name]: event.target.value});
};

const handleChangeDueDate = (selectedDate) => {
      setFormState({...formState, dueDate: selectedDate.toDate()});
};

```

Don't forget to add a `name` property to all textFields for this implementation to work

2023-05-14 10:31 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
> +	};
You can get rid of this as you will have the formData state

2023-05-14 10:31 UTC, cezarmocanu requested changes

2023-05-14 10:31 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
>  import { useDispatch } from "react-redux";
Also remove this import

2023-05-14 10:35 UTC, AleBarboni commented on src/components/modal-content/CreateTask.jsx
>  import { useDispatch } from "react-redux";
I use dispatch at:
onClick={() => dispatch(closeModal())}

2023-05-16 11:39 UTC, AleBarboni commented on src/components/modal-content/CreateTask.jsx
>  import { useDispatch } from "react-redux";
without useDispatch the close button doesn't work

2023-05-16 16:59 UTC, merged