108 fc7 create task modal content
cezarmocanu/semicolon-task-manager-skillbrains pull request #5
Opened 2023-04-20 16:12 UTC by AleBarboni

2023-04-21 21:50 UTC, soringifei approved these changes

2023-04-22 10:57 UTC, cezarmocanu requested changes

2023-04-22 10:57 UTC, cezarmocanu commented on src/components/CreateTaskItems.jsx
> +const OPTIONS = [
This approach of creating constants is not correct:
- jsx files are expected to have a jsx return function iside them such as a react component, if there is no jsx the file should be js
- the file is in the components folder even though it is not a component
- the name OPTIONS is too general an can be easily mixed up

Usually constants should be added in the constants folder, as a .js file. In this particular case, there is no need for other components to use the OPTIONS, so the best approach is to leave this variable in the component file(modal-content/CreateTask) right above the component function

2023-04-22 10:57 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
> +import OPTIONS from "../CreateTaskItems";
Please remove the import and add the options as a local constant

2023-04-22 10:58 UTC, cezarmocanu requested changes

2023-04-22 10:58 UTC, cezarmocanu commented on src/components/modal-content/CreateTask.jsx
> +												<MenuItem key={option.label} value={option.label}>
Please also check this issue in the console
![image](https://user-images.githubusercontent.com/15773819/233780077-844e1569-5062-4eb5-9e32-ac8711a9a4c4.png)

2023-04-23 10:31 UTC, HalaszPaul approved these changes

2023-04-23 19:51 UTC, soringifei approved these changes

2023-05-02 15:22 UTC, ovidiufilip10 approved these changes

2023-05-02 17:12 UTC, AleBarboni commented on src/components/modal-content/CreateTask.jsx
> +												<MenuItem key={option.label} value={option.label}>
done

2023-05-02 17:20 UTC, cezarmocanu approved these changes

2023-05-02 17:21 UTC, merged