674 aab tasks service
cezarmocanu/semicolon-task-manager-skillbrains pull request #7
Opened 2023-04-23 08:42 UTC by HalaszPaul

2023-05-02 15:28 UTC, ovidiufilip10 requested changes
Please remove unnecessary whitespaces from the code.

2023-05-02 16:45 UTC, cezarmocanu requested changes

2023-05-02 16:45 UTC, cezarmocanu commented on src/constants/api.js
> +		GET_TASKS:(workspaceId) => `${API}/v1/workspaces/${workspaceId}/tasks`,
ALL_TASKS

2023-05-02 16:45 UTC, cezarmocanu commented on src/services/tasks-service.js
> +return data.items;
review formatting

2023-05-02 16:45 UTC, cezarmocanu commented on src/constants/api.js
> +	TASKS:{
Add test with use effect in test page

2023-05-02 16:45 UTC, cezarmocanu commented on src/services/tasks-service.js
> +return data.items;
data is enough because it has no items property

2023-05-02 16:45 UTC, cezarmocanu commented on src/store/slices/tasks-slice.js
> +        items: [],
modifyt everywhere to tasks

2023-05-08 16:06 UTC, cezarmocanu approved these changes

2023-05-08 16:07 UTC, AdrianaGroza approved these changes

2023-05-08 16:07 UTC, OanaIv approved these changes

2023-05-08 16:07 UTC, MariusStan2001 approved these changes

2023-05-08 17:01 UTC, merged